### ISSUE TITLE
Aqueous soil doesn't work well with other mods

### ISSUE THREAD

**Issue by slayer6409** [MysticMods/Roots#313] opened 2019-10-04 09:22 UTC
When using a way to boost crop growth speed from other mods like the Astral Sorcery Aevitas ritual or Nourishers from Hearth Well, Aqueous soil no longer harvests plants automatically. When I stop using the Nourishers/ritual they work as expected.

**Comment by duely** [comment] 2019-10-04 11:17
That's... strange. It would entirely depend on how those mods function, although there should be a fallback that randomly checks for a fully grown crop on random ticks and harvests it if that's the case... I'll look into it, thanks.

**Comment by slayer6409** [comment] 2019-10-04 19:27
It could be that I didn't wait long enough for the fallback to kick in, but I've been watching my wheat and sugarcane for a while. The wheat is working, but the sugar cane is just staying fully grown. It looks like the fallback is working except for sugarcane.

**Comment by majijn** [comment] 2019-10-04 20:50
if the soil gets a block update like a redstone pulse it harvests the crops when this happens

having neighboring plants usually helps with the updates and stuff, but yeah, they get stuck (and i forgot to make an issue for this)

**Comment by slayer6409** [comment] 2019-10-04 21:04
Yeah that seems to work for everything except sugarcane, so for now I will have to use other methods for sugarcane.

**Comment by duely** [comment] 2019-10-05 01:11
The problem is the crop growth event not consistently firing...

**Comment by Davoleo** [comment] 2019-10-05 15:13
you could use the block tick method that runs once after a specified amount of ticks passed, but then crop growth would lose their randomness properties

**Comment by noobanidus** [comment] 2020-02-25 11:25
Okay, I'm now directly calling the harvest function regardless. It's possible there was a bug in my original code, perhaps there still is, but every random tick will attempt to harvest grown plants above.

**Comment by noobanidus** [comment] 2020-02-27 13:18
I've done the best I can and I'm aiming for a 3.1 wide test release this weekend, so I'm closing this issue for now. If it's still an issue, we can re-open and re-address.

**Closed by noobanidus** 2020-02-27 13:18 UTC
Labels: 3.1.0, bug, investigate, mod integration
