### ISSUE TITLE
Geas has no effect on hostile mobs besides a visual cue

### ISSUE THREAD

**Issue by VallenFrostweaver** [MysticMods/Roots#241] opened 2019-09-11 16:42 UTC
Minecraft: 1.12.2
Roots: 3.0.13
Forge: 14.23.5.2838
Geas produces an effect above the target but the target does not change behavior.

**Comment by duely** [comment] 2019-09-29 03:06
I'm closing the issue; if it still is non-functional in the next release, I'm not sure what the cause is.

**Closed by duely** 2019-09-29 03:06 UTC
Labels: bug, next release
