### ISSUE TITLE
CraftTweaker Support Not Functioning For Animal Harvest/Pacifist

### ISSUE THREAD

**Issue by squirrelkiller** [MysticMods/Roots#181] opened 2019-08-23 10:14 UTC
Unknown if anything beyond pacifist and animal harvest are broken, but those two are both broken.
Forge: 14.23.5.2838
Mods: [modlist.txt](https://github.com/MysticMods/Roots/files/3534018/modlist.txt)

All other useful files:

[crafttweaker.log](https://github.com/MysticMods/Roots/files/3534007/crafttweaker.log)

RootsAnimalHarvest.zs
```
import mods.roots.AnimalHarvest;

//Waddles
AnimalHarvest.addEntity(<entity:waddles:adelie_penguin>);
```
RootsPacifist.zs
```
import mods.roots.Pacifist;

//Waddles
Pacifist.addEntity(<entity:waddles:adelie_penguin>);
```

**Comment by duely** [comment] 2019-08-23 10:31
Caused by #182 and a typo. Will be fixed in next release, see #182 for updates.

**Closed by duely** 2019-08-23 10:31 UTC
