### ISSUE TITLE
Can't Use two Apothicary Pouches?

### ISSUE THREAD

**Issue by daforsyth** [MysticMods/Roots#353] opened 2019-11-02 04:02 UTC
### General Information

**Describe the bug:**
When using two apothecary pouches in Roots, your wand will look into the first one in your hotbar. If the first doesn't have the needed ingredients but the second one does your spell won't cast.

Not sure if this is intended but it would be nice if you could use multiple bags as each bag only has 6 vials for holding different ingredients are there is more then 6 ingredients for spells in-game. 

**To Reproduce:**
1. Have a Pouch with 1 ingredient
2. Have a Pouch with another ingredient in hotbar
3. Use a spell that requires both ingredients

**Expected behavior:**
When you use a spell it searches through all your apothecary bags for ingredients.

Environment Versions
Roots-1.12.2-3.0.19.jar

Mystic Mods Versions

MysticalLib: mysticalworld-1.12.2-1.5.0.jar
Other Versions:

Forge: forge-14.23.5.2847
Minecraft: 1.12.2
Modpack (if available): Bewitchment Discord Server Pack (On Twitch)

![2019-11-01_23 03 12](https://user-images.githubusercontent.com/14133907/68065779-f5a91300-fcfb-11e9-816e-6a03169470cb.png)
![2019-11-01_23 03 16](https://user-images.githubusercontent.com/14133907/68065780-f772d680-fcfb-11e9-855b-e337724bb8cf.png)
![2019-11-01_23 04 17](https://user-images.githubusercontent.com/14133907/68065792-183b2c00-fcfc-11e9-9aaa-5b2e29178b50.png)

**Comment by Birgliss** [comment] 2019-11-02 04:13
dupe of #208, closing

(we appreciate the report, but please check the [known issues list](https://github.com/MysticMods/Roots/issues/183))

**Closed by Birgliss** 2019-11-02 04:13 UTC
Labels: bug, duplicate
